### PR TITLE
[#1471] Add remaining roll tables defined in SRD

### LINKED ISSUE #1471: Add other tables from the SRD
There are a variety of roll tables mixed throughout the SRD that would be useful:

### Spells
- Confusion
- Reincarnate

### Items
- Armor of Resistance*
- Bag of Beans
- Gray/Rust/Tan Bags of Tricks
- Candle of Invocation*
- Carpet of Flying*
- Efreeti Bottle
- Feather Token*
- Horn of Valhalla*
- Iron Flask*
- Manual of Golems*
- Necklace of Prayer Beads*
- Potion of Resistance*
- Ring of Resistance*
- Robe of Useful Items*
- Sphere of Annihilation
- Wand of Wonder

\* *These items only used the roll tables on item creation by DMs, not on usage.*

### Others
- Four tables in the "Creating Sentient Magic Items" section

### PR DESCRIPTION
**Pull request by kjolern**
Added rolltables and linked them to their items. Fixes #1471

### CODE REVIEW

**Review by arbron — CHANGES_REQUESTED** [review]
For the links to the tables in descriptions, it would be better to link to the roll table in the text if possible, rather than putting it at the end:

Current:
Screen Shot 2022-08-24 at 12 38 30

Suggestion:
Screen Shot 2022-08-24 at 12 38 54

**Review by arbron — CHANGES_REQUESTED** [review]
The table names should be capitalized the same as the item names: "Carpet of flying" => "Carpet of Flying"

**Review by arbron — CHANGES_REQUESTED** [review]
For any of the tables that select between a list of items, they should contain compendium links rather than just text:

Screen Shot 2022-08-24 at 12 44 43

**Comment by arbron** [comment]
The SRD journal entry (Chapter 11: DM Tools) should link to the Sentient Magic Item roll tables now that they exist.

**Review by arbron — CHANGES_REQUESTED** [review]
There a few of the tables that include dice rolls that should be converted to inline rolls:

Bag of Beans Now:
`5d4 toadstools sprout. If a creature eats a toadstool, roll any die. On an odd roll, the eater must succeed on a DC 15 Constitution saving throw or take 5d6 poison damage and become poisoned for 1 hour. On an even roll, the eater gains 5d6 temporary hit points for 1 hour.`

Converted:
`[[5d4]] toadstools sprout. If a creature eats a toadstool, roll any die. On an odd roll, the eater must succeed on a DC 15 Constitution saving throw or take [[/r 5d6]] poison damage and become poisoned for 1 hour. On an even roll, the eater gains [[/r 5d6]] temporary hit points for 1 hour.`

Automatic inline rolls (e.g. `[[5d4]]`) should be used for any effects that happen once as soon as the item is rolled (in this case, as soon as the beans are used you determine the count).

Rollable inline rolls (e.g. `[[/r 5d6]]`) should be used for anything that might need to be rolled more than once (in this case, damage after each of the beans is consumed).

**Review by arbron — CHANGES_REQUESTED** [review]
The information on berserkers summoned and requirements were lost during the `Horn of Valhalla` conversion. You should probably edit the description to add that back in for each of the four types. Possibly something like this added between the 3rd & 4th paragraphs:

`This silver horn summons 2d4 + 2 berserkers when blown.`

`This brass horn summons 3d4 + 3 berserkers when blown and requires proficiency with all simple weapons to be used.`

**Review by arbron — CHANGES_REQUESTED** [review]
For `Necklace of Prayer Beads`, I believe it would be clearer to revert back to the original table in the description, and then only including the text for each bead type in the roll table.

**Review by arbron — CHANGES_REQUESTED** [review]
Rather than including the size and other details of the `Carpet of Flying` in the roll table, I think that would be a good item to convert to four variants with the details included in the description.

`This carpet is 3 ft. x 5 ft. and has a speed of 80 feet carrying up to 200 lb., or half that speed when carrying up to 400 lb.`

**Comment by Fyorl** [comment]
@kjolern Sorry, this was accidentally closed. Feel free to re-open it and target it at the `2.0.x` branch for now.

**Comment by kjolern** [comment]
No worries @Fyorl .  But I'm going to make som changes anyway so I think it will be cleaner to start fresh and make a new PR. Do you still want me to target it at the 2.0.x branch ?

**Comment by Fyorl** [comment]
Yeah, please target it at `2.0.x`, thanks

**Pull request closed without merging**
