### PR TITLE
Update loot sheet with tabs

### PR DESCRIPTION
**Pull request by tavernaDelBeerholder**
Several modules tend to work with the concept of adding a tab to the item sheet unfortunately the loot sheet is the only one that "thinks" differently, to make it uniform and help developers can we put the tabs back to the loot sheet ?
I also think it is visually better because then people find the same coporting.

### CODE REVIEW

**Comment by p4535992** [comment]
Just a clarification is the pr okay to point it to 2.3.x or should I point it directly to 2.4.X ?

**Comment by Fyorl** [comment]
> Just a clarification is the pr okay to point it to 2.3.x or should I point it directly to 2.4.X ?

I will typically re-target branches just before I merge them. But if you'd like to do it yourself, that's fine too, it will save me from accidentally making a mistake and merging it into `2.3.x`.

**Comment by p4535992** [comment]
I beg you to consider this PR

**Comment by Fyorl** [comment]
> I beg you to consider this PR

The PR is small and uncontroversial so I have placed it in the milestone. The only delay is that I need to do a little bit of testing before merging, which I haven't had time for yet.

**Review by Fyorl — APPROVED** [review]

**Pull request merged**
