### PR TITLE
[#2607] Fix collpased accordion sections not opening after editing description

### PR DESCRIPTION
**Pull request by arbron**
~~This fix at least ensures that the contents of the accordion are always visible, but it doesn't animate for the first expanding after changing another property. I would welcome thoughts as to a better fix.~~

Found a better fix that properly stores the height.

> [!Note]
> I switched from using `setTimeout` to `requestAnimationFrame` for the accordion timing here because it felt more appropriate, but that isn't part of the actual bug fix.

### CODE REVIEW

**Comment by Fyorl** [comment]
I tracked this to a regression caused by the changes here: https://github.com/foundryvtt/dnd5e/pull/2573/files#diff-48f5cd8733c53432fef055aab117363d87bf159c8a3088a567bca60dbf4af90e

If we remove those lines, the issue goes away. I am having trouble reproducing the issue that those lines were meant to fix, so perhaps we could just remove them? Or perhaps address the issue they are fixing in a different way?

**Comment by arbron** [comment]
> I tracked this to a regression caused by the changes here: https://github.com/foundryvtt/dnd5e/pull/2573/files#diff-48f5cd8733c53432fef055aab117363d87bf159c8a3088a567bca60dbf4af90e
> 
> If we remove those lines, the issue goes away. I am having trouble reproducing the issue that those lines were meant to fix, so perhaps we could just remove them? Or perhaps address the issue they are fixing in a different way?

If I remove those lines this is what I get:

https://github.com/foundryvtt/dnd5e/assets/19979839/19d09c6c-6cd2-4f3c-9edf-ada8645c8848

Might be a browser-specific issue.

**Comment by Fyorl** [comment]
Yeah I don't experience any flash when I tested it, but it is deliberately allowing them to render at full size in order to get the correct height, so I can see why it would happen. It might be related to browsers, or just general FPS and monitor refresh rate. It's fine to solve it with some extra calls to `getBoundingClientRect` then if it avoids that issue.

**Review by Fyorl — CHANGES_REQUESTED** [review]
We should consider if `bind`, `_onExpandSection` and `_onCollapseSection` still need to be `async`. Might be best that they're not in order to avoid implying that the sections are collapsed or expanded when the Promise resolves, because that actually only happens in `_onEnd`.

**Review by Fyorl — APPROVED** [review]

**Pull request merged**
