### PR TITLE
[#1539] Add identifiers to spells

### PR DESCRIPTION
**Pull request by arbron**
This adds an `identifier` field to spells and sets them up on the SRD. This should be useful in identifying matching spells, representing spell lists, applying advancements to spells, and more.

This also modifies the default method for creating slugs to support spells with slashes like `"Blindness/Deafness"`. Formerly that would have created the identifier `blindnessdeafness` and now it adds a dash in the middle to create `blindness-deafness`.

### CODE REVIEW

**Comment by Varriount** [comment]
How is this different from a spell's name?

**Comment by arbron** [comment]
> How is this different from a spell's name? Is this something that would also make sense for other item types (features, regular items, etc.)?

The key difference between this and names is that this is stable regardless of localization. This should allow for building spell lists and certain other features without relying solely on full UUIDs.

I think the other item type that might most benefit from this is `feat`, which would allow some more powerful features in the advancements system. I figure that could be done as a separate PR though.

**Comment by Varriount** [comment]
I think that this would be useful to implement for all item types, as it would allow, for example, a module to synchronize updates between items in a player's character sheet, the "unassociated" items available in the `items` sidebar, and items in compendiums. This is actually a real-world request I've made for the DDB Importer module: https://github.com/MrPrimate/ddb-importer/issues/251

**Comment by p4535992** [comment]
the same mechanism should be implemented for effects with the addition of an "identifier" field.

**Pull request closed without merging**
