### PR TITLE
Make icon use currency abbreviation

### PR DESCRIPTION
**Pull request by cstby**
Currently, the currency icons depend on the object key in `CONFIG.DND5E.currenices`. This is not ideal because it means these icons will be mismatched if a module patches the currencies object.

This pull requests updates the inventory template that that it will use icons based on the currency abbreviations, which can be patched by https://github.com/cstby/foundryvtt-world-currency-5e.

### CODE REVIEW

**Comment by arbron** [comment]
Not a feasible change, because those abbreviations might be localized, and we don't want to force localization modules to update a whole bunch of CSS just to change those abbreviations.

**Comment by cstby** [comment]
That's totally understandable.

What would you think about providing the icon specifications in the currencies config object? That would allow modules to remap the icon without running into the localization issue you mentioned above.

**Comment by cstby** [comment]
Updated the pull request to give you a concrete idea of the proposal above.

**Comment by Larkinabout** [comment]
Could the config contain the path to the image itself instead, so that they could be swapped out with other images without further messing with the CSS? I can only think of replacing the classes with a style tag with the url populated in the template.

**Comment by arbron** [comment]
Closed in favor of https://github.com/foundryvtt/dnd5e/pull/3155

**Pull request closed without merging**
