### PR TITLE
[#3250] Aggregate damage types before passing to `applyDamage`

### PR DESCRIPTION
**Pull request by arbron**
Adds a new dice helper function `aggregateDamageRolls` which splits and re-combines damage rolls based on the roll's type, term flavor, and optionally any roll properties. This function is then used by `ChatMessage5e#applyChatCardDamage` before rolls are totaled to ensure that damage types are properly split.

The function starts by using a `chunkTerms` helper function which goes through the terms in a roll grouping into chunks based on the operators. Addition and subtraction cause new chunks to be created while multiplication and division are included in the same chunk. This is so that a damage type defined in flavor of a term can spread to other terms that it is multiplied or divided with. So if you have a formula `1d6 + 5 * 1d4[fire]` that has the overall type of piercing, the `1d6` will remaining piercing while the `5 * 1d4` will all be treated as fire.

Once the chunking is complete then chunks from all different rolls are combined into lists of terms grouped by type and properties (so long as the `respectProperties` option is set, otherwise they will only be grouped by type). These sets are then converted into new `DamageRoll`s with options set appropriately.

### CODE REVIEW

**Comment by krbz999** [comment]
Does it make sense to use this somewhere early in `Item5e#rollDamage`?

**Comment by arbron** [comment]
> Does it make sense to use this somewhere early in `Item5e#rollDamage`?

Maybe…though this was written without taking into account things like unresolved string terms so it might lead to issues if we try it before the rolls occur. For example if the formula is `1d6 + @mod + @attackBonus` (piercing) and then the data includes `{ attackBonus: "2d8[radiant]" }`, we don't have the information available to properly split damages until those terms are resolved.

If we wait until after the terms are resolved during the rolling process, then we are creating brand new rolls before they are saved to the chat message, so the saved rolls are different than what was actually rolled.

Perhaps something we can look at in the future, but for now it feels better to save the data as-rolled and do this processing after the fact when we actually need the aggregation.

**Review by Fyorl — COMMENTED** [review]
How does this overlap with `ChatMessage5e#_aggregateDamageRoll`? It seems they do fairly similar things. Can we simplify that method at all by delegating some of the work to these helpers?

**Comment by arbron** [comment]
> How does this overlap with `ChatMessage5e#_aggregateDamageRoll`? It seems they do fairly similar things. Can we simplify that method at all by delegating some of the work to these helpers?

This should be able to be used in concert with that, but since that method has some extra work to do I didn't want to work on it in the same PR.

**Review by Fyorl — APPROVED** [review]
Just one potential issue, then it looks good to merge.

**Pull request merged**
