### PR TITLE
[#1351] Allow spells to be linked to a specific class

### LINKED ISSUE #1351: Assign Spells by Class
Originally in GitLab by @danz5000

Might it be possible to assign spells to class, and thus assign spell attacks and DCs according to the class? That way we could organize how many spells we have according to which class, which class it's assigned to when multiclassing, and other quality of life improvements.

It would also allow us to differentiate having a Bloodwell Vial (applies only to sorcerer spells) vs. a Moon Sickle (applies only to druid spells) vs. a Wand of the Warmage (applies to all spell attacks).

### PR DESCRIPTION
**Pull request by absymylyar**
Closes #1351

### CODE REVIEW

**Review by arbron — APPROVED** [review]
I'm going to tentatively mark this in for `3.3.x` because I think we want to be able to handle it with the followup changes and not leave it partially implemented, but I'm not sure if we'll have time to review all the changes for `3.2.x`. I'll keep glances at the other PRs in this set so we can have everything in as good a state as possible before then.

**Comment by absymylyar** [comment]
That's fine, it will give me time to test those changes with my players.
By the way, is there a Discord ?

**Comment by arbron** [comment]
> That's fine, it will give me time to test those changes with my players. By the way, is there a Discord ?

The official Foundry Discord, you can find a link on the Foundry site.

**Comment by arbron** [comment]
@absymylyar Could you pop over to the issue (https://github.com/foundryvtt/dnd5e/issues/1351) and give it a comment so I can assign it to you?

**Comment by absymylyar** [comment]
Done

**Pull request merged**
