### PR TITLE
[#1334] Support variables in Duration field of items

### LINKED ISSUE #1334: Suggestion: Support variables in Duration field of items
Originally in GitLab by @Mary-Usagi

It would be great if item sheets would support variables in the `Duration` field, like in the max value for `Limited Uses`.

image

### PR DESCRIPTION
**Pull request by kaelad02**
Add support for variables in the Duration field of items. Also update some of the class features and spells in the compendiums to use it.

### CODE REVIEW

**Comment by kaelad02** [comment]
@Fyorl Do we not want this feature anymore? I don't personally need it, so I'm not asking because of that. Or did you just close it because it was going to merge into an old branch? I can rebase if necessary

**Comment by Fyorl** [comment]
This was accidentally closed when the branch was moved to `2.0.x`. We're working on re-opening them.

**Comment by kaelad02** [comment]
@Fyorl Is there any schema for the item's system data that I should update too? I don't recall seeing any of that anywhere, but I figured I should ask.

**Comment by arbron** [comment]
> @Fyorl Is there any schema for the item's system data that I should update too? I don't recall seeing any of that anywhere, but I figured I should ask.

No schema yet, that is something I am working on so I'll make the necessary changes in my branch once this is merged :).

**Review by Fyorl — APPROVED** [review]
I think there's an opportunity to refactor some of the shared code around validation and preparation of these deterministic formula strings. If we stored a list of these attributes somewhere (maybe in config?):

```js
[{
	property: "system.uses.max",
	label: "DND5E.LimitedUses"
}, {
	property: "system.duration.value",
	label: "DND5E.Duration"
}]
```

I think that would allow us to consolidate the code in `Item5e#prepareMaxUses` and `Item5e#prepareDurationValue`, as well as in `ItemSheet5e#_getSubmitData`.

We can merge this in as-is and take it from there though.

**Pull request merged**
