### PR TITLE
Spell sorting

### PR DESCRIPTION
**Pull request by absymylyar**
Add spell sort within each levels, first by name, then by "always prepared" status and finally by "prepared" status

### CODE REVIEW

**Comment by arbron** [comment]
New sheets already have the option of switching between alphabetic sorting and manual sorting, and this change makes it impossible to use manual sorting on the legacy sheets, so unless you can give a good reason to take away that ability I'll probably say this won't be changed.

**Comment by absymylyar** [comment]
Maybe this kind of sorting can be proposed as an additional automatic sorting (or in place of alphabetic sorting) to highlight spells by priority.
This diplay is far better
2024-03-26_11h28_00

**Comment by Fyorl** [comment]
We can add a new sorting method, but it will need the associated UI to go along with it.

**Comment by absymylyar** [comment]
I add this sorting as an option

**Comment by Fyorl** [comment]
Seems like this got rebased on top of one of your other branches rather than the `3.2.x` or `3.1.x` branch? Could you rebase it onto `3.2.x` so that this PR only contains the changes for spell sorting?

**Pull request closed without merging**
