### PR TITLE
Fix number of Telepathic Bond targets

### PR DESCRIPTION
**Pull request by TheGiddyLimit**
The spell reads:

> You forge a telepathic link among up to eight willing creatures of your choice within range, psychically linking each creature to all the others for the duration. Creatures with Intelligence scores of 2 or less aren't affected by this spell.
> Until the spell ends, the targets can communicate telepathically through the bond whether or not they have a common language. The communication is possible over any distance, though it can't extend to other planes of existence.

### CODE REVIEW

**Review by arbron — CHANGES_REQUESTED** [review]
Rebase this atop the `v10-dev` branch and I'll see about getting it into `2.0`.

**Review by arbron — CHANGES_REQUESTED** [review]
Some changes were made to `spells.db` since you rebased (whoops). Could you run `compilePacks` again to resolve the merge issue?

**Comment by TheGiddyLimit** [comment]
FYI when I run `npm run build:db` it changes more than just the `Telepathic Bond` line (stripping out a bunch of `"_stats": ...` by the look?); have only committed that one line

**Comment by arbron** [comment]
> FYI when I run `npm run build:db` it changes more than just the `Telepathic Bond` line (stripping out a bunch of `"_stats": ...` by the look?); have only committed that one line

That's fine, we're probably going to update our scripts to strip that data anyway.

**Review by arbron — APPROVED** [review]

**Review by aaclayton — APPROVED** [review]

**Pull request merged**
